version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - '5432:5432'
